### ISSUE TITLE
Setup protobuf file based on spec components

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos-controller#38]
### Due Date: xx/xx/2x

# Description
<pre>
Place description here
</pre>

# UAT
<pre>
Place UAT here
</pre>

# Deployment Steps
<pre>
Place steps here
</pre>

# SubTasks
- [ ]
- [ ]
- [ ]

**Comment by RandyDeo** [comment]
This would be difficult/not optimal for various reasons 
- proto files have several declarations needed such as the service and messages
- A particular message needs to be defined and also numbered (once declared and in use, a message cannot be reorganized etc. so thought needs to be placed into the initial setup and order etc)
- A service needs to be declared and an rpc line which indicates what message input is required for a function and the message which will be returned 

Therefore, even if this could be setup based on config, there will still need to be manual setup and tweaking to make sure the orders etc are as intended/reliable.
